version: '3.4'

volumes:
  node_modules:
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bullet-manager
    ports:
      - '3306:3306'
  back:
    build: .
    restart: always
    environment:
      - DATABASE_URL=mysql://${DB_USER}:${DB_PASSWORD}@${DOCKER_DB_HOST}:${DB_PORT}/${DB_NAME}
    ports:
      - 3001:3001
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
      - ./components:/usr/src/app/components
      - ./exceptions:/usr/src/app/exceptions
      - ./helpers:/usr/src/app/helpers
      - ./middleware:/usr/src/app/middleware
      - ./prisma:/usr/src/app/prisma
      - ./utils:/usr/src/app/utils
    depends_on:
      - db
    tty: true
    stdin_open: true
