version: '3.4'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bullet-manager
    ports:
      - '3306:3306'
  back:
    build: .
    restart: always
    environment:
      - DATABASE_URL=mysql://${DB_USER}:${DB_PASSWORD}@${DOCKER_DB_HOST}:${DB_PORT}/${DB_NAME}
    ports:
      - 3001:3001
    volumes:
      - .:/app
      - ./components:/app/components
      - ./exceptions:/app/exceptions
      - ./helpers:/app/helpers
      - ./middleware:/app/middleware
      - ./prisma:/app/prisma
      - ./utils:/app/utils
      - node_modules:/app/node_modules
    depends_on:
      - db
    tty: true
    stdin_open: true
volumes:
  node_modules:
